root = "."
tmp_dir = "/tmp"

[build]
  args_bin = []
  bin = "/bin/myapp"
  cmd = "go build -gcflags=\"all=-N -l\" -o /bin/myapp ."
  full_bin = "dlv --headless=true --listen=:2345 --api-version=2 --accept-multiclient exec --continue /bin/myapp"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
