services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Dev
      args:
        APP_ENV: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
