services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - '${PORT:-3333}:${PORT:-3333}'
      - '${DEBUG_PORT:-2345}:${DEBUG_PORT:-2345}'
    env_file:
      - .env
    volumes:
      - .:/app
